### PR TITLE
js: config.js: Fix newline character handling in data-isso-* i18n strings

### PR DESCRIPTION
**Pull request by pkvach**
## Checklist
- [x] All new and existing **tests are passing**
- [x] I have added an entry to CHANGES.rst because this is a user-facing change or an important bugfix
- [x] I have written **proper commit message(s)**
      

## What changes does this Pull Request introduce?

Replace escaped newline characters in data-isso attribute values with actual newline characters to ensure correct parsing and display.

## Why is this necessary?

Fixes https://github.com/posativ/isso/issues/912

Example of a non-working configuration from a related issue:
```
 <script data-isso="//comments.test.com/" src="//comments.test.com/js/count.min.js"
    data-isso-num-comments-text-en="One comment\n{{ n }} comments"></script>
```

### CODE REVIEW

**Comment by jelmer** [comment]
please complete the checklist in the PR template

**Comment by pkvach** [comment]
Added an entry to CHANGES.rst

**Comment by jelmer** [comment]
Hmm, not sure what is up with the CI here - can you rebase on main?

**Comment by pkvach** [comment]
Sure, I've rebased the changes.

**Comment by jelmer** [comment]
Hmm, some of the actions don't seem to run for this PR?

**Comment by pkvach** [comment]
I'm not sure if I can get them to launch.

**Comment by pkvach** [comment]
I think some checks didn't run because there are no changes to the `*.py` files in this PR.

**Comment by jelmer** [comment]
> I think some checks didn't run because there are no changes to the `*.py` files in this PR.

Ah, good call - fixed in https://github.com/isso-comments/isso/pull/1004. Can you rebase past that PR?

**Comment by pkvach** [comment]
@jelmer 
Thank you for your help. 
It looks like in order for tests to run, changes are needed in this workflow:
https://github.com/isso-comments/isso/blob/6dffaa74f1184280f45a8bf64730f3d153c74b05/.github/workflows/python-tests.yml

**Comment by pkvach** [comment]
All checks passed after I rebased onto https://github.com/isso-comments/isso/pull/1004.

**Comment by ix5** [comment]
Hey @pkvach, thank you for this PR! I see you (were) on a roll here with proposing a lot of useful fixes with great descriptions and tests. Sorry you had to wait so long for review.

I only have one suggestion to make in order to clean up that whole code block while you're at it (in a separate commit). Either way, your code as-is is fine as well.

```
diff --git a/isso/js/app/config.js b/isso/js/app/config.js
index 8684e8d..4ce92fb 100644
--- a/isso/js/app/config.js
+++ b/isso/js/app/config.js
@@ -17,25 +17,24 @@ for (var i = 0; i < js.length; i++) {
         var attr = js[i].attributes[j];
         if (/^data-isso-/.test(attr.name)) {
 
+            // Normalize underscores to dashes so that language-specific
+            // strings can be caught better later on, e.g.
+            // data-isso-postbox-text-text-PT_BR becomes postbox-text-text-pt-br.
+            // Also note that attr.name only gives lowercase strings as per HTML
+            // spec, e.g. data-isso-FOO-Bar becomes foo-bar, but since the test
+            // environment's jest-environment-jsdom seemingly does not follow
+            // that convention, convert to lowercase here anyway.
+            const attrName = attr.name.substring(10)
+                       .replace(/_/g, '-')
+                       .toLowerCase()
+
             // Replace escaped newline characters in the attribute value with actual newline characters
             const attrValue = attr.value.replace(/\\n/g, '\n');
 
             try {
-                // Normalize underscores to dashes so that language-specific
-                // strings can be caught better later on,
-                // e.g. data-isso-postbox-text-text-PT_BR becomes
-                // postbox-text-text-pt-br.
-                // Also note that attr.name only gives lowercase strings as per
-                // HTML spec, e.g. data-isso-FOO-Bar becomes foo-bar, but since
-                // the test environment's jest-environment-jsdom seemingly does
-                // not follow that convention, convert to lowercase here anyway.
-                config[attr.name.substring(10)
-                       .replace(/_/g, '-')
-                       .toLowerCase()] = JSON.parse(attrValue);
+                config[attrName] = JSON.parse(attrValue);
             } catch (ex) {
-                config[attr.name.substring(10)
-                       .replace(/_/g, '-')
-                       .toLowerCase()] = attrValue;
+                config[attrName] = attrValue;
             }
         }
     }
```

**Review by ix5 — APPROVED** [review]

**Comment by pkvach** [comment]
@ix5
Thank you for your feedback. I appreciate it.
I have made the changes you suggested.

**Comment by ix5** [comment]
Nice, thank you for your contribution!

**Comment by Kerumen** [comment]
@ix5 Do you think you can release this change? Thanks 🙏🏻

**Pull request merged**
