### PR TITLE
isso: html.py: Prevent auto creation of invalid links in comments

### PR DESCRIPTION
**Pull request by pkvach**
## Checklist
- [x] All new and existing **tests are passing**
- [x] I have added an entry to CHANGES.rst because this is a user-facing change or an important bugfix
- [x] I have written **proper commit message(s)**
      

## What changes does this Pull Request introduce?

- Enhanced the `Sanitizer` class in `isso/utils/html.py` to prevent the automatic creation of invalid links by:
modifying the `set_links` function to reject new links, allowing only existing links to be modified. This change addresses the issue where text could be misinterpreted as a domain name, leading to the creation of invalid links.

- Updated tests in `isso/tests/test_html.py` to include new cases that ensure:
text that could be misinterpreted as links, such as 'ld.so' and file paths, are not automatically converted into links.

## Why is this necessary?
Fixes https://github.com/posativ/isso/issues/557

### CODE REVIEW

**Review by jelmer — APPROVED** [review]

**Review by jelmer — CHANGES_REQUESTED** [review]
Please fix the linting issues. LGTM otherwise.

**Comment by jelmer** [comment]
please complete the checklist in the PR template and fix lint

**Comment by pkvach** [comment]
Added an entry to CHANGES.rst

**Comment by pkvach** [comment]
Fixed linting issues.

**Review by jelmer — APPROVED** [review]

**Comment by ix5** [comment]
Sorry for the late reply, thank you @pkvach for this fix.

**Pull request merged**
