### PR TITLE
Fixing error message: URI {uri} does not exist

### PR DESCRIPTION
**Pull request by Lucas-C**
## Checklist
- [x] All new and existing **tests are passing**
- [NA] (If adding features:) I have added tests to cover my changes
- [NA] (If docs changes needed:) I have updated the **documentation** accordingly.
- [NA] I have added an entry to `CHANGES.rst` because this is a user-facing change or an important bugfix
- [x] I have written **proper commit message(s)**

## What changes does this Pull Request introduce?
Previous to this one-line fix, the following error message could be returned:

    URI does not exist %s

Now the error message containes the actual URI:

    URI {uri} does not exist

## Why is this necessary?
To help debug problems! 🙂

### CODE REVIEW

**Comment by jelmer** [comment]
The change overall LGTM, thanks! Do translations play well with f-strings?

**Comment by jelmer** [comment]
What's going on with the failing e2e test?

**Comment by Lucas-C** [comment]
Seems like the CI pipeline fails due to "screenshots not matching".

But this PR should not have any visual impact.

Maybe the reference screenshots should be updated in a separate PR?
The process is detailed in this documentation section: https://github.com/isso-comments/isso/blob/master/docs/docs/technical-docs/testing-client.rst#screenshot-comparison

**Review by jelmer — APPROVED** [review]

**Comment by simsinght** [comment]
Kind of unrelated, but I'm trying to debug an issue where I keep getting the older `URI does not exist %s`. I see its because I'm using the official docker image, and it hasn't been built for over 2 months so likely doesn't contain this change. 

What would trigger the docker image to rebuild?

**Comment by BBaoVanC** [comment]
> Kind of unrelated, but I'm trying to debug an issue where I keep getting the older `URI does not exist %s`. I see its because I'm using the official docker image, and it hasn't been built for over 2 months so likely doesn't contain this change.
> 
> What would trigger the docker image to rebuild?

Are you using docker compose, and if so, either the `image:` or `build:`? Depending on which you're using, either `docker compose pull` or `docker compose build` should update it.

**Pull request merged**
