### PR TITLE
change GitHub organization

### PR DESCRIPTION
**Pull request by posativ**
Change `posativ/isso` to `isso-comments/isso`

Not sure if docs/news.rst or CHANGES.rst should also be edited.

### CODE REVIEW

**Comment by jelmer** [comment]
> Not sure if docs/news.rst or CHANGES.rst should also be edited.

I think I can see an argument either way. It would be good for consistency, but also CHANGES a historic record, so might make sense to keep the original lines. It doesn't seem likely that the redirect will break.

So let's keep this as is for now? Other changes LGTM.

**Review by jelmer — APPROVED** [review]

**Comment by BBaoVanC** [comment]
> think I can see an argument either way. It would be good for consistency, but also CHANGES a historic record, so might make sense to keep the original lines.

In my opinion the concern should be whether the document is a working historical record, not that text written years ago stays unmodified. I personally would update all the links to the new URL, but given that GitHub would make redirects it doesn't really matter unless something changes with GitHub or something in the future.

**Comment by jelmer** [comment]
> > think I can see an argument either way. It would be good for consistency, but also CHANGES a historic record, so might make sense to keep the original lines.
> 
> In my opinion the concern should be whether the document is a working historical record, not that text written years ago stays unmodified. I personally would update all the links to the new URL, but given that GitHub would make redirects it doesn't really matter unless something changes with GitHub or something in the future.

Your quote seems strip out the last line from my reply, which said pretty much the same thing.

**Comment by jelmer** [comment]
This looks good to me as-is, and hasn't had any more comments so I think we should just land it.

**Pull request merged**
