### PR TITLE
Invert screenshot for dark color theme

### PR DESCRIPTION
**Pull request by oberrich**
## Checklist
- [x] Did none of the above
## What changes does this Pull Request introduce?
This inverts the screenshots on the README of this repo.

## Why is this necessary?
My eyes, bug prevention

For comparison see [`patch-1`](https://github.com/oberrich/isso/tree/patch-1?tab=readme-ov-file#screenshot) vs. [`master`](https://github.com/oberrich/isso?tab=readme-ov-file#screenshot). You may want to change the URL of the dark mode logo so it doesn't go away when I delete the `patch-1` tag.

### CODE REVIEW

**Comment by jelmer** [comment]
Please include the assets in the repo, rather than outside of it.

I guess doing this adds to the burden of updating the screenshot if we need to refresh it in the future. Not a big deal, but worth pointing out.

**Comment by oberrich** [comment]
I don't think the screenshot is hosted inside the repo, if I copy & paste the image directly into my clone of this repository it uploads it to `github.com/oberrich`, so I guess the best place I can host this image for you is right here:
image

**Comment by ix5** [comment]
The screenshot not being hosted inside the repo is due to me updating it from an external source (posativ.org) to one uploaded to the corresponding PR: https://github.com/isso-comments/isso/pull/867

That wasn't the correct way to do it, we should add the light (and potentially dark mode) screenshots to this repo and link them from inside the markdown. I think GitHub's markdown parser can resolve (relative) links to files inside the _current_ repo so that we don't have to hardcode the path to `user-images.githubusercontent.com` (example: `Isso in action`). That way, forks updating the screenshot files inside their repo don't have to wonder why the README image doesn't update.

Then again, if we want the images displayed correctly on PyPI, we need hardcoded paths, no?
Probably something like `https://raw.githubusercontent.com/isso-comments/isso/master/isso/img/isso.svg` is what we want, then.

As for re-generating the screenshots: I've tried to document that a bit inside https://github.com/isso-comments/isso-marketing-material but maybe someone can submit a PR to add a `Dockerfile` to automate that step.

**Comment by oberrich** [comment]
`isso/img/` and hard coded URI is probably most reasonable and portable.

**Comment by ix5** [comment]
> `isso/img/` and absolute URL is probably most reasonable and portable.

Sounds good. Please add a commit that places both images (light and dark) there and update the README (in another commit) to reference them.

Would also be nice to have a quickly reproducible way to (automatically) regenerate the screenshots.

**Comment by oberrich** [comment]
> > `isso/img/` and absolute URL is probably most reasonable and portable.
> 
> Sounds good. Please add a commit that places both images (light and dark) there and update the README (in another commit) to reference them.
> 
> Would also be nice to have a quickly reproducible way to (automatically) regenerate the screenshots.

Feel free to commit it on your own, I've decided not to spend any more time on this issue.

**Pull request closed without merging**
