### PR TITLE
comments: Fix total comments count calculation

### PR DESCRIPTION
**Pull request by pkvach**
## Checklist
- [x] All new and existing **tests are passing**
- [x]  I have added an entry to CHANGES.rst because this is a user-facing change or an important bugfix
- [x] I have written **proper commit message(s)**
      

## What changes does this Pull Request introduce?

Changes to properly count hidden comments when calculating the total number of comments.

- `isso/views/comments.py`: The calculation of total_replies is modified. Instead of directly assigning the value of reply_counts[root_id] to total_replies, it now calculates the sum of all values in reply_counts if root_id is None, otherwise it assigns the value of reply_counts[root_id].

- `isso/js/embed.js`: The redundant incrementation of the count variable with comment.total_replies was removed.

- `isso/tests/test_comments.py`: Several assertions are added to various test cases to check the value of total_replies in the response data.

## Why is this necessary?

Fixes https://github.com/isso-comments/isso/issues/448

### Demo
- Before fix

image

- After fix

image

### CODE REVIEW

**Comment by jelmer** [comment]
please complete the checklist in the PR template

**Comment by pkvach** [comment]
Added an entry to CHANGES.rst

**Comment by pkvach** [comment]
Please make a review of this PR.

**Review by ix5 — COMMENTED** [review]
Changes itself LGTM.

I found this really hard to review because of the terminologies (some values point are dicts (`replies`) and others are integers (`hidden_replies`), the request param `parent` becomes `id` in the response, and the meaning/calculation of `reply_counts` was hard to wrap my head around). The existing code is quite clunky and I'm glad you nevertheless took the time to look into it and fix this longstanding issue @pkvach.

Please fix the two identically-named commits (either squash or split the tests/CHANGES changes into appropriately named commits)

**Comment by pkvach** [comment]
@ix5 
Thank you for the review! You're right, it was a tricky one. 
To make things easier to follow, I've reformatted the changes into a single Git commit.

**Review by ix5 — APPROVED** [review]
Thanks for squashing, LGTM

**Pull request merged**
