### PR TITLE
css: Add CSS variables for better organization and flexibility

### PR DESCRIPTION
**Pull request by pkvach**
## Checklist
- [x] All new and existing **tests are passing**
- [x] I have added an entry to `CHANGES.rst` because this is a user-facing change or an important bugfix
- [x] I have written **proper commit message(s)**
      

## What changes does this Pull Request introduce?

Added CSS variables to improve theme customization and organization in `isso.css`.

## Why is this necessary?

Closes https://github.com/isso-comments/isso/issues/655

### CODE REVIEW

**Review by jelmer — APPROVED** [review]

**Comment by ix5** [comment]
Nice work, very cleanly done. LGTM as well.

---

One thing though: I'll reiterate what I wrote in 

> I do not have a particularly strong opinion on this either way. But I agree with @ vincentbernat in testing before blindly rewriting everything.
>
> As a data point: https://caniuse.com/css-variables
>
> Browsers from 2017 (Edge) might not support it. IE 10 doesn't support it. Many big-C Corporate/Enterprise people are still on LTS versions, one way or another. Also, Android 4.4 devices are still working perfectly fine.
> Also, switching the CSS would break existing setups with custom CSS, so it'd require a version bump and a notice to users.

This is potentially a breaking change as it drops support for IE10 (not sure whether we were compatible before, but now we definitely aren't). We should communicate that somewhere (changelog) and also drop the claim from the homepage ([docs/index.html](https://github.com/isso-comments/isso/blob/c257a4fe9490632bc29abc1dc294847bab06fcc7/docs/index.html#L35)) about IE10 compatibility.

**Comment by pkvach** [comment]
Thank you for your attention to this matter.

I understand that there may be differing opinions regarding whether to continue supporting a browser that is still in use but no longer receives updates from its developer, leaving it vulnerable to security risks.

If needed, I can help with restoring support for IE 10 after this PR change.

**Comment by ix5** [comment]
> Thank you for your attention to this matter.
> 
> I understand that there may be differing opinions regarding whether to continue supporting a browser that is still in use but no longer receives updates from its developer, leaving it vulnerable to security risks.
> 
> If needed, I can help with restoring support for IE 10 after this PR change.

I might have miscommunicated here, IE10 support is not that important to me, but rather our claims to be compatible when we aren't anymore.

**Comment by pkvach** [comment]
Great, thanks for clarifying.
Should I correct the documentation where IE10 support is listed? 
And maybe add a note to the “Changes.rst” file.

**Comment by ix5** [comment]
> Great, thanks for clarifying. Should I correct the documentation where IE10 support is listed? And maybe add a note to the `CHANGES.rst` file.

Already done https://github.com/isso-comments/isso/pull/1022

**Pull request merged**
